/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swing;

import clases.Cliente;
import clases.ConexionExist;
import clases.Empleado;
import clases.Libro;

import java.awt.BorderLayout;
import java.util.List;
import javax.swing.*;

/**
 *
 * @author leiii
 */
public class NuevoCliente extends javax.swing.JPanel {
    
    JPanel panelPagina;
    List<Cliente> clientes;
    ConexionExist conexion = new ConexionExist();
    Empleado emp;

    /**
     * Creates new form NuevoCliente
     */
    public NuevoCliente(JPanel panelPagina, Empleado emp) {
        initComponents();
        
        this.panelPagina = panelPagina;
        this.emp = emp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        botonAnadir = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        contrasena = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        nombre = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        apellido = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        botonCancelar = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(91, 78, 202));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NUEVO CLIENTE");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 700, 40));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Usuario:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Contraseña:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Nombre:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Apellido:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        botonAnadir.setBackground(new java.awt.Color(161, 154, 224));
        botonAnadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonAnadirMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Añadir Cliente");

        javax.swing.GroupLayout botonAnadirLayout = new javax.swing.GroupLayout(botonAnadir);
        botonAnadir.setLayout(botonAnadirLayout);
        botonAnadirLayout.setHorizontalGroup(
            botonAnadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonAnadirLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(20, 20, 20))
        );
        botonAnadirLayout.setVerticalGroup(
            botonAnadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        add(botonAnadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 150, 30));

        usuario.setForeground(new java.awt.Color(102, 102, 102));
        usuario.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        usuario.setBorder(null);
        add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 260, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 260, 20));

        contrasena.setForeground(new java.awt.Color(102, 102, 102));
        contrasena.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        contrasena.setBorder(null);
        add(contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 260, -1));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 260, 10));

        nombre.setForeground(new java.awt.Color(102, 102, 102));
        nombre.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        nombre.setBorder(null);
        add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 260, -1));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 260, 10));

        apellido.setForeground(new java.awt.Color(102, 102, 102));
        apellido.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        apellido.setBorder(null);
        add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 260, -1));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 260, 10));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Teléfono:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));

        telefono.setForeground(new java.awt.Color(102, 102, 102));
        telefono.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        telefono.setBorder(null);
        add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 260, -1));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 260, 10));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Email:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, -1));

        email.setForeground(new java.awt.Color(102, 102, 102));
        email.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        email.setBorder(null);
        add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 260, -1));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 260, 10));

        botonCancelar.setBackground(new java.awt.Color(161, 154, 224));
        botonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonCancelarMousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cancelar");

        javax.swing.GroupLayout botonCancelarLayout = new javax.swing.GroupLayout(botonCancelar);
        botonCancelar.setLayout(botonCancelarLayout);
        botonCancelarLayout.setHorizontalGroup(
            botonCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonCancelarLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel9)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        botonCancelarLayout.setVerticalGroup(
            botonCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 150, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void botonAnadirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAnadirMousePressed
        try {
            int tlf = Integer.parseInt(telefono.getText());
            if (usuario.getText().isBlank() || contrasena.getText().isBlank() || nombre.getText().isBlank() || apellido.getText().isBlank() || String.valueOf(telefono).length() != 9 || email.getText().isBlank()){
                JOptionPane.showMessageDialog(null, "Compruebe que todos los datos están rellenados");
            } else {
                int id;
                clientes = conexion.cargarClientes();
                if (clientes.size() == 0) {
                    id = 1;
                } else {
                    id = clientes.get(clientes.size() - 1).getId() + 1;
                }
                Cliente nuevoCliente = new Cliente(id, usuario.getText(), contrasena.getText(), nombre.getText(), apellido.getText(), tlf, email.getText());
                conexion.anadirCliente(nuevoCliente, emp);
                JOptionPane.showMessageDialog(null, "El cliente se ha añadido correctamente");
                Clientes frame = new Clientes(panelPagina, emp);
                frame.setSize(700,550);
                frame.setLocation(0,0);
                panelPagina.removeAll();
                panelPagina.add(frame, BorderLayout.CENTER);
                panelPagina.revalidate();
                panelPagina.repaint();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Introduce valores correctos");
        }
    }//GEN-LAST:event_botonAnadirMousePressed

    private void botonCancelarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCancelarMousePressed
        Clientes frame = new Clientes(panelPagina, emp);
        frame.setSize(700,550);
        frame.setLocation(0,0);
        panelPagina.removeAll();
        panelPagina.add(frame, BorderLayout.CENTER);
        panelPagina.revalidate();
        panelPagina.repaint();
    }//GEN-LAST:event_botonCancelarMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido;
    private javax.swing.JPanel botonAnadir;
    private javax.swing.JPanel botonCancelar;
    private javax.swing.JTextField contrasena;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField telefono;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
