/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swing;

import clases.ConexionExist;
import clases.Empleado;
import clases.Libro;
import clases.Prestamo;

import java.awt.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

import scrollbar.ScrollBarCustom;
import table.TableHeader;

/**
 *
 * @author leiii
 */
public class Prestamos extends javax.swing.JPanel {
    String[] nombreColumnas = {"Id Libro", "Id Cliente", "Fecha"};
    JPanel panelPagina;
    List<Prestamo> prestamos = new ArrayList<Prestamo>();
    ConexionExist conexion = new ConexionExist();
    Empleado emp;
    TableRowSorter<DefaultTableModel> sorter;

    /**
     * Creates new form Prestamos
     */
    public Prestamos(JPanel panelPagina, Empleado emp) {
        initComponents();
        
        this.panelPagina = panelPagina;
        this.emp = emp;
        
        tabla_prestamos.setShowHorizontalLines(true);
        tabla_prestamos.setGridColor(new Color(230,230,230));
        tabla_prestamos.setRowHeight(33);
        tabla_prestamos.getTableHeader().setReorderingAllowed(true);
        tabla_prestamos.getTableHeader().setDefaultRenderer(new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                TableHeader header = new TableHeader(value + "");
                if(column==nombreColumnas.length){
                    header.setHorizontalAlignment(JLabel.CENTER);
                }
                return header;
            }
       });
       jScrollPane1.getViewport().setBackground(Color.WHITE);
       jScrollPane1.setVerticalScrollBar(new ScrollBarCustom());
       fixtable(jScrollPane1);
       modificarTabla();
    }
    
    public void fixtable(JScrollPane scroll) {
        scroll.getViewport().setBackground(Color.WHITE);
        scroll.setVerticalScrollBar(new ScrollBarCustom());
        JPanel p = new JPanel();
        scroll.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
        scroll.setBorder(new EmptyBorder(5, 10, 5, 10));
    }

    public void cargarDatos() {
        prestamos.clear();
        prestamos = conexion.cargarPrestamos();
    }

    public void modificarTabla() {
        cargarDatos();
        //Nombre de las columnas y cargamos los datos al array que se le van a enviar al la tabla para cargar los datos
        int cantidad = prestamos.size();
        String[][] d = new String[cantidad][3];
        for (int i = 0; i < prestamos.size(); i++) {
            d[i][0] = String.valueOf(prestamos.get(i).getIdlibro());
            d[i][1] = String.valueOf(prestamos.get(i).getIdcliente());
            d[i][2] = String.valueOf(prestamos.get(i).getFecha());
        }
        //se carga el modelo de la tabla
        DefaultTableModel model = new DefaultTableModel(d, nombreColumnas){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
            
        };
        tabla_prestamos.setModel(model);
        tabla_prestamos.setAutoCreateRowSorter(true);
        sorter = new TableRowSorter<>(model);
        tabla_prestamos.setRowSorter(sorter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_prestamos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        botonVer = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        botonNuevo = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        botonEliminar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textoBuscar = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla_prestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla_prestamos.setSelectionBackground(new java.awt.Color(161, 154, 224));
        jScrollPane1.setViewportView(tabla_prestamos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 119, 550, 420));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("PRÉSTAMOS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        botonVer.setBackground(new java.awt.Color(91, 78, 202));
        botonVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonVerMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa25x25.png"))); // NOI18N

        javax.swing.GroupLayout botonVerLayout = new javax.swing.GroupLayout(botonVer);
        botonVer.setLayout(botonVerLayout);
        botonVerLayout.setHorizontalGroup(
            botonVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonVerLayout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        botonVerLayout.setVerticalGroup(
            botonVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonVerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(botonVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 60, -1));

        botonNuevo.setBackground(new java.awt.Color(91, 78, 202));
        botonNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonNuevoMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/plus.png"))); // NOI18N

        javax.swing.GroupLayout botonNuevoLayout = new javax.swing.GroupLayout(botonNuevo);
        botonNuevo.setLayout(botonNuevoLayout);
        botonNuevoLayout.setHorizontalGroup(
            botonNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonNuevoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        botonNuevoLayout.setVerticalGroup(
            botonNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonNuevoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(botonNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 60, -1));

        botonEliminar.setBackground(new java.awt.Color(91, 78, 202));
        botonEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonEliminarMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/minus.png"))); // NOI18N

        javax.swing.GroupLayout botonEliminarLayout = new javax.swing.GroupLayout(botonEliminar);
        botonEliminar.setLayout(botonEliminarLayout);
        botonEliminarLayout.setHorizontalGroup(
            botonEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonEliminarLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(16, 16, 16))
        );
        botonEliminarLayout.setVerticalGroup(
            botonEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(botonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, 60, -1));

        jLabel2.setText("Buscar:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        textoBuscar.setBorder(null);
        textoBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textoBuscarKeyReleased(evt);
            }
        });
        add(textoBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 350, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 350, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void botonVerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVerMousePressed
        if (tabla_prestamos.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Para ver más información debes seleccionar un préstamo de la tabla");
        } else {
            int id = Integer.parseInt(tabla_prestamos.getValueAt(tabla_prestamos.getSelectedRow(), 0).toString());
            Prestamo prestamo = null;
            prestamos.clear();
            prestamos = conexion.cargarPrestamos();
            for (int i = 0; i < prestamos.size(); i++) {
                if(prestamos.get(i).getId() == id){
                    prestamo = prestamos.get(i);
                }
            }
            if (prestamo != null) {
                VerPrestamo frame = new VerPrestamo(panelPagina, emp, prestamo);
                frame.setSize(700, 550);
                frame.setLocation(0, 0);
                panelPagina.removeAll();
                panelPagina.add(frame, BorderLayout.CENTER);
                panelPagina.revalidate();
                panelPagina.repaint();
            } else {
                JOptionPane.showMessageDialog(null, "Para ver más información debes seleccionar un préstamo de la tabla");
            }
        }
    }//GEN-LAST:event_botonVerMousePressed

    private void botonNuevoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonNuevoMousePressed
        cargarDatos();
        NuevoPrestamo frame = new NuevoPrestamo(panelPagina, emp);
        frame.setSize(700,550);
        frame.setLocation(0,0);
        panelPagina.removeAll();
        panelPagina.add(frame, BorderLayout.CENTER);
        panelPagina.revalidate();
        panelPagina.repaint();
    }//GEN-LAST:event_botonNuevoMousePressed

    private void botonEliminarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEliminarMousePressed
        if (tabla_prestamos.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Para eliminar debes seleccionar un préstamo de la tabla");
        } else {
            //Obtencion del id del objeto seleccionaod en la tabla
            int id = Integer.parseInt(tabla_prestamos.getValueAt(tabla_prestamos.getSelectedRow(), 0).toString());
            conexion.eliminarPrestamo(id);
        }
        modificarTabla();
    }//GEN-LAST:event_botonEliminarMousePressed

    private void textoBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textoBuscarKeyReleased
        sorter.setRowFilter(RowFilter.regexFilter("(?i)"+textoBuscar.getText()));
    }//GEN-LAST:event_textoBuscarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonEliminar;
    private javax.swing.JPanel botonNuevo;
    private javax.swing.JPanel botonVer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tabla_prestamos;
    private javax.swing.JTextField textoBuscar;
    // End of variables declaration//GEN-END:variables
}
