/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing;

import clases.Empleado;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author leiii
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    Empleado emp;
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal(Empleado emp) {
        initComponents();
        
        this.emp = emp;
        
        Home frame = new Home();
        frame.setSize(700,550);
        frame.setLocation(0,0);
        panelPagina.removeAll();
        panelPagina.add(frame, BorderLayout.CENTER);
        panelPagina.revalidate();
        panelPagina.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        botonHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bordeHome = new javax.swing.JPanel();
        botonLibros = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bordeLibros = new javax.swing.JPanel();
        botonPrestamos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        bordePrestamos = new javax.swing.JPanel();
        botonClientes = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        bordeClientes = new javax.swing.JPanel();
        botonCerrarSesion = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        botonConsultas = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        bordeConsultas = new javax.swing.JPanel();
        panelPagina = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(91, 78, 202));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonHome.setBackground(new java.awt.Color(161, 154, 224));
        botonHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonHomeMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Home");

        bordeHome.setBackground(new java.awt.Color(255, 255, 255));
        bordeHome.setPreferredSize(new java.awt.Dimension(5, 0));

        javax.swing.GroupLayout bordeHomeLayout = new javax.swing.GroupLayout(bordeHome);
        bordeHome.setLayout(bordeHomeLayout);
        bordeHomeLayout.setHorizontalGroup(
            bordeHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        bordeHomeLayout.setVerticalGroup(
            bordeHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout botonHomeLayout = new javax.swing.GroupLayout(botonHome);
        botonHome.setLayout(botonHomeLayout);
        botonHomeLayout.setHorizontalGroup(
            botonHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonHomeLayout.createSequentialGroup()
                .addComponent(bordeHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(136, Short.MAX_VALUE))
        );
        botonHomeLayout.setVerticalGroup(
            botonHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bordeHome, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addGroup(botonHomeLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel2.add(botonHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 200, 50));

        botonLibros.setBackground(new java.awt.Color(91, 78, 202));
        botonLibros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonLibrosMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Libros");

        bordeLibros.setBackground(new java.awt.Color(91, 78, 202));
        bordeLibros.setPreferredSize(new java.awt.Dimension(5, 50));

        javax.swing.GroupLayout bordeLibrosLayout = new javax.swing.GroupLayout(bordeLibros);
        bordeLibros.setLayout(bordeLibrosLayout);
        bordeLibrosLayout.setHorizontalGroup(
            bordeLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        bordeLibrosLayout.setVerticalGroup(
            bordeLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout botonLibrosLayout = new javax.swing.GroupLayout(botonLibros);
        botonLibros.setLayout(botonLibrosLayout);
        botonLibrosLayout.setHorizontalGroup(
            botonLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonLibrosLayout.createSequentialGroup()
                .addComponent(bordeLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(0, 138, Short.MAX_VALUE))
        );
        botonLibrosLayout.setVerticalGroup(
            botonLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bordeLibros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(botonLibrosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(botonLibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 200, -1));

        botonPrestamos.setBackground(new java.awt.Color(91, 78, 202));
        botonPrestamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonPrestamosMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Préstamos");

        bordePrestamos.setBackground(new java.awt.Color(91, 78, 202));
        bordePrestamos.setPreferredSize(new java.awt.Dimension(5, 50));

        javax.swing.GroupLayout bordePrestamosLayout = new javax.swing.GroupLayout(bordePrestamos);
        bordePrestamos.setLayout(bordePrestamosLayout);
        bordePrestamosLayout.setHorizontalGroup(
            bordePrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        bordePrestamosLayout.setVerticalGroup(
            bordePrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout botonPrestamosLayout = new javax.swing.GroupLayout(botonPrestamos);
        botonPrestamos.setLayout(botonPrestamosLayout);
        botonPrestamosLayout.setHorizontalGroup(
            botonPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonPrestamosLayout.createSequentialGroup()
                .addComponent(bordePrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        botonPrestamosLayout.setVerticalGroup(
            botonPrestamosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonPrestamosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addContainerGap(18, Short.MAX_VALUE))
            .addComponent(bordePrestamos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(botonPrestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, -1));

        botonClientes.setBackground(new java.awt.Color(91, 78, 202));
        botonClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonClientesMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Clientes");

        bordeClientes.setBackground(new java.awt.Color(91, 78, 202));
        bordeClientes.setPreferredSize(new java.awt.Dimension(5, 50));

        javax.swing.GroupLayout bordeClientesLayout = new javax.swing.GroupLayout(bordeClientes);
        bordeClientes.setLayout(bordeClientesLayout);
        bordeClientesLayout.setHorizontalGroup(
            bordeClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        bordeClientesLayout.setVerticalGroup(
            bordeClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout botonClientesLayout = new javax.swing.GroupLayout(botonClientes);
        botonClientes.setLayout(botonClientesLayout);
        botonClientesLayout.setHorizontalGroup(
            botonClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonClientesLayout.createSequentialGroup()
                .addComponent(bordeClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(127, Short.MAX_VALUE))
        );
        botonClientesLayout.setVerticalGroup(
            botonClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonClientesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addContainerGap(18, Short.MAX_VALUE))
            .addComponent(bordeClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(botonClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 200, -1));

        botonCerrarSesion.setBackground(new java.awt.Color(91, 78, 202));
        botonCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonCerrarSesionMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cerrar Sesión");

        javax.swing.GroupLayout botonCerrarSesionLayout = new javax.swing.GroupLayout(botonCerrarSesion);
        botonCerrarSesion.setLayout(botonCerrarSesionLayout);
        botonCerrarSesionLayout.setHorizontalGroup(
            botonCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonCerrarSesionLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addGap(0, 93, Short.MAX_VALUE))
        );
        botonCerrarSesionLayout.setVerticalGroup(
            botonCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonCerrarSesionLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel6)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel2.add(botonCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 200, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ReaderPanda_pequeno.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 20, -1, -1));

        botonConsultas.setBackground(new java.awt.Color(91, 78, 202));
        botonConsultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonConsultasMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Registros");

        bordeConsultas.setBackground(new java.awt.Color(91, 78, 202));
        bordeConsultas.setPreferredSize(new java.awt.Dimension(5, 50));

        javax.swing.GroupLayout bordeConsultasLayout = new javax.swing.GroupLayout(bordeConsultas);
        bordeConsultas.setLayout(bordeConsultasLayout);
        bordeConsultasLayout.setHorizontalGroup(
            bordeConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        bordeConsultasLayout.setVerticalGroup(
            bordeConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout botonConsultasLayout = new javax.swing.GroupLayout(botonConsultas);
        botonConsultas.setLayout(botonConsultasLayout);
        botonConsultasLayout.setHorizontalGroup(
            botonConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonConsultasLayout.createSequentialGroup()
                .addComponent(bordeConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        botonConsultasLayout.setVerticalGroup(
            botonConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonConsultasLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7)
                .addContainerGap(18, Short.MAX_VALUE))
            .addComponent(bordeConsultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(botonConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 200, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 550));

        panelPagina.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelPaginaLayout = new javax.swing.GroupLayout(panelPagina);
        panelPagina.setLayout(panelPaginaLayout);
        panelPaginaLayout.setHorizontalGroup(
            panelPaginaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        panelPaginaLayout.setVerticalGroup(
            panelPaginaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        jPanel1.add(panelPagina, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 700, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonHomeMousePressed
        darColor(botonHome, bordeHome);
        devolverColor(botonLibros, bordeLibros);
        devolverColor(botonPrestamos, bordePrestamos);
        devolverColor(botonClientes, bordeClientes);
        devolverColor(botonConsultas, bordeConsultas);

        Home frame = new Home();
        frame.setSize(700,550);
        frame.setLocation(0,0);
        panelPagina.removeAll();
        panelPagina.add(frame, BorderLayout.CENTER);
        panelPagina.revalidate();
        panelPagina.repaint();
    }//GEN-LAST:event_botonHomeMousePressed

    private void botonLibrosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLibrosMousePressed
        darColor(botonLibros, bordeLibros);
        devolverColor(botonHome, bordeHome);
        devolverColor(botonPrestamos, bordePrestamos);
        devolverColor(botonClientes, bordeClientes);
        devolverColor(botonConsultas, bordeConsultas);
        
        Libros frame = new Libros(panelPagina, emp);
        frame.setSize(700,550);
        frame.setLocation(0,0);
        panelPagina.removeAll();
        panelPagina.add(frame, BorderLayout.CENTER);
        panelPagina.revalidate();
        panelPagina.repaint();
    }//GEN-LAST:event_botonLibrosMousePressed

    private void botonPrestamosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonPrestamosMousePressed
        darColor(botonPrestamos, bordePrestamos);
        devolverColor(botonHome, bordeHome);
        devolverColor(botonLibros, bordeLibros);
        devolverColor(botonClientes, bordeClientes);
        devolverColor(botonConsultas, bordeConsultas);
        
        Prestamos frame = new Prestamos(panelPagina, emp);
        frame.setSize(700,550);
        frame.setLocation(0,0);
        panelPagina.removeAll();
        panelPagina.add(frame, BorderLayout.CENTER);
        panelPagina.revalidate();
        panelPagina.repaint();
    }//GEN-LAST:event_botonPrestamosMousePressed

    private void botonClientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonClientesMousePressed
        darColor(botonClientes, bordeClientes);
        devolverColor(botonHome, bordeHome);
        devolverColor(botonLibros, bordeLibros);
        devolverColor(botonPrestamos, bordePrestamos);
        devolverColor(botonConsultas, bordeConsultas);
        
        Clientes frame = new Clientes(panelPagina, emp);
        frame.setSize(700,550);
        frame.setLocation(0,0);
        panelPagina.removeAll();
        panelPagina.add(frame, BorderLayout.CENTER);
        panelPagina.revalidate();
        panelPagina.repaint();
    }//GEN-LAST:event_botonClientesMousePressed

    private void botonCerrarSesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCerrarSesionMousePressed
        Login frame = new Login();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonCerrarSesionMousePressed

    private void botonConsultasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonConsultasMousePressed
        darColor(botonConsultas, bordeConsultas);
        devolverColor(botonHome, bordeHome);
        devolverColor(botonLibros, bordeLibros);
        devolverColor(botonPrestamos, bordePrestamos);
        devolverColor(botonClientes, bordeClientes);
        
        Registros frame = new Registros();
        frame.setSize(700,550);
        frame.setLocation(0,0);
        panelPagina.removeAll();
        panelPagina.add(frame, BorderLayout.CENTER);
        panelPagina.revalidate();
        panelPagina.repaint();
    }//GEN-LAST:event_botonConsultasMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal(new Empleado(1, "Ejemplo", true)).setVisible(true);
            }
        });
    }
    
    private void darColor(JPanel pane, JPanel borde) {
        pane.setBackground(new Color(161, 154, 224));
        borde.setBackground(new Color(255,255,255));
    }
    
    private void devolverColor(JPanel pane, JPanel borde) {
        pane.setBackground(new Color(91, 78, 202));
        borde.setBackground(new Color(91, 78, 202));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bordeClientes;
    private javax.swing.JPanel bordeConsultas;
    private javax.swing.JPanel bordeHome;
    private javax.swing.JPanel bordeLibros;
    private javax.swing.JPanel bordePrestamos;
    private javax.swing.JPanel botonCerrarSesion;
    private javax.swing.JPanel botonClientes;
    private javax.swing.JPanel botonConsultas;
    private javax.swing.JPanel botonHome;
    private javax.swing.JPanel botonLibros;
    private javax.swing.JPanel botonPrestamos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelPagina;
    // End of variables declaration//GEN-END:variables
}
