/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swing;

import clases.ConexionExist;
import clases.Empleado;
import clases.Libro;
import java.awt.BorderLayout;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author leiii
 */
public class VerLibro extends javax.swing.JPanel {

    JPanel panelPagina;
    List<Libro> libros;
    ConexionExist conexion = new ConexionExist();
    Empleado emp;
    
    /**
     * Creates new form VerLibro
     */
    public VerLibro(JPanel panelPagina, Empleado emp, Libro libro) {
        initComponents();
        
        this.panelPagina = panelPagina;
        this.emp = emp;

        titulo.setText(libro.getTitulo());
        autor.setText(libro.getAutor());
        genero.setText(libro.getGenero());
        editorial.setText(libro.getEditorial());
        idioma.setText(libro.getIdioma());
        numPaginas.setText(String.valueOf(libro.getNumpaginas()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        autor = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        genero = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        editorial = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        idioma = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        numPaginas = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        botonVolver = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(91, 78, 202));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 700, 40));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Autor:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Género:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Editorial:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        autor.setEditable(false);
        autor.setBackground(new java.awt.Color(255, 255, 255));
        autor.setForeground(new java.awt.Color(102, 102, 102));
        autor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        autor.setBorder(null);
        add(autor, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 260, -1));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 260, 10));

        genero.setEditable(false);
        genero.setBackground(new java.awt.Color(255, 255, 255));
        genero.setForeground(new java.awt.Color(102, 102, 102));
        genero.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        genero.setBorder(null);
        add(genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 260, -1));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 260, 10));

        editorial.setEditable(false);
        editorial.setBackground(new java.awt.Color(255, 255, 255));
        editorial.setForeground(new java.awt.Color(102, 102, 102));
        editorial.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        editorial.setBorder(null);
        add(editorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 260, -1));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 260, 10));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Idioma:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        idioma.setEditable(false);
        idioma.setBackground(new java.awt.Color(255, 255, 255));
        idioma.setForeground(new java.awt.Color(102, 102, 102));
        idioma.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        idioma.setBorder(null);
        add(idioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 260, -1));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 260, 10));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Número de páginas:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, -1));

        numPaginas.setEditable(false);
        numPaginas.setBackground(new java.awt.Color(255, 255, 255));
        numPaginas.setForeground(new java.awt.Color(102, 102, 102));
        numPaginas.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        numPaginas.setBorder(null);
        add(numPaginas, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 260, -1));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 260, 10));

        botonVolver.setBackground(new java.awt.Color(161, 154, 224));
        botonVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonVolverMousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Volver");

        javax.swing.GroupLayout botonVolverLayout = new javax.swing.GroupLayout(botonVolver);
        botonVolver.setLayout(botonVolverLayout);
        botonVolverLayout.setHorizontalGroup(
            botonVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonVolverLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(50, 50, 50))
        );
        botonVolverLayout.setVerticalGroup(
            botonVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        add(botonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 150, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVolverMousePressed
        Libros frame = new Libros(panelPagina, emp);
        frame.setSize(700,550);
        frame.setLocation(0,0);
        panelPagina.removeAll();
        panelPagina.add(frame, BorderLayout.CENTER);
        panelPagina.revalidate();
        panelPagina.repaint();
    }//GEN-LAST:event_botonVolverMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField autor;
    private javax.swing.JPanel botonVolver;
    private javax.swing.JTextField editorial;
    private javax.swing.JTextField genero;
    private javax.swing.JTextField idioma;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField numPaginas;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
