/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swing;

import clases.ConexionExist;
import clases.Empleado;
import clases.Libro;
import clases.Prestamo;
import java.awt.BorderLayout;
import java.util.Date;
import java.util.List;
import javax.swing.JPanel;
import javax.xml.crypto.Data;

/**
 *
 * @author leiii
 */
public class VerPrestamo extends javax.swing.JPanel {

    JPanel panelPagina;
    List<Prestamo> prestamos;
    ConexionExist conexion = new ConexionExist();
    Empleado emp;
    
    /**
     * Creates new form VerPrestamo
     */
    public VerPrestamo(JPanel panelPagina, Empleado emp, Prestamo prestamo) {
        initComponents();
        
        this.panelPagina = panelPagina;
        this.emp = emp;

        libro.setText(String.valueOf(prestamo.getIdlibro()));
        cliente.setText(String.valueOf(prestamo.getIdcliente()));
        fecha.setText(String.valueOf(prestamo.getFecha()));
        diasPrestamo.setText(String.valueOf(prestamo.getDiasprestamo()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        fecha = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        botonVolver = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        libro = new javax.swing.JTextField();
        cliente = new javax.swing.JTextField();
        diasPrestamo = new javax.swing.JTextField();

        jLabel7.setText("jLabel7");

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(91, 78, 202));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PRÉSTAMO");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 700, 40));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Id Libro:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Id Cliente:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Fecha:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Dias de préstamo:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 260, 20));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 260, 10));

        fecha.setEditable(false);
        fecha.setBackground(new java.awt.Color(255, 255, 255));
        fecha.setForeground(new java.awt.Color(102, 102, 102));
        fecha.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        fecha.setBorder(null);
        add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 260, -1));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 260, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 260, 10));

        botonVolver.setBackground(new java.awt.Color(161, 154, 224));
        botonVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonVolverMousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Volver");

        javax.swing.GroupLayout botonVolverLayout = new javax.swing.GroupLayout(botonVolver);
        botonVolver.setLayout(botonVolverLayout);
        botonVolverLayout.setHorizontalGroup(
            botonVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonVolverLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel9)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        botonVolverLayout.setVerticalGroup(
            botonVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        add(botonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 150, 30));

        libro.setEditable(false);
        libro.setBackground(new java.awt.Color(255, 255, 255));
        libro.setForeground(new java.awt.Color(102, 102, 102));
        libro.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        libro.setBorder(null);
        add(libro, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 260, -1));

        cliente.setEditable(false);
        cliente.setBackground(new java.awt.Color(255, 255, 255));
        cliente.setForeground(new java.awt.Color(102, 102, 102));
        cliente.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        cliente.setBorder(null);
        add(cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 260, -1));

        diasPrestamo.setEditable(false);
        diasPrestamo.setBackground(new java.awt.Color(255, 255, 255));
        diasPrestamo.setForeground(new java.awt.Color(102, 102, 102));
        diasPrestamo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        diasPrestamo.setBorder(null);
        add(diasPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 260, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVolverMousePressed
        Prestamos frame = new Prestamos(panelPagina, emp);
        frame.setSize(700,550);
        frame.setLocation(0,0);
        panelPagina.removeAll();
        panelPagina.add(frame, BorderLayout.CENTER);
        panelPagina.revalidate();
        panelPagina.repaint();
    }//GEN-LAST:event_botonVolverMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonVolver;
    private javax.swing.JTextField cliente;
    private javax.swing.JTextField diasPrestamo;
    private javax.swing.JTextField fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField libro;
    // End of variables declaration//GEN-END:variables
}
